### ISSUE TITLE
Wrong Action In Learn Mode

### ISSUE THREAD

**Issue by BradyHammond** [reputage/seedQuestAssets#77]
- Selecting a wrong action in learn mode doesn't add to progress bar, but does increment the action count.
- This also causes the game progression to work incorrectly.

**Comment by westonb7** [comment]
I've made e temporary fix for this in the Seed_bugfixing branch. Selecting the wrong action in learn mode is still possible, but it no longer increments the action count, and shouldn't affect game progression. Still needs a visual update so that the green checkmark no longer appears when an incorrect action is taken.

**Comment by BradyHammond** [comment]
I added an ex for a wrong interactable selection.
